apiVersion: v1
kind: Service
metadata:
  name: user-subscription-service
spec:
  selector:
    app: user-subscription-service
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  type: LoadBalancer
