apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  selector:
    app: weather-api-service
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
  type: ClusterIP # Internal communication only within the cluster.
