apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  selector:
    app: weather-api-service
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  type: LoadBalancer
